#define REGIDRAGO_SIM_NO_MAIN
#include "../src/regidrago_sim.cpp"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>

namespace sim {

struct EngineTestAccess {};

}  // namespace sim

namespace {

std::filesystem::path repo_root() {
  const std::filesystem::path current = std::filesystem::current_path();
  if (std::filesystem::exists(current / "SIM-PLAN.md")) return current;
  if (std::filesystem::exists(current.parent_path() / "SIM-PLAN.md")) {
    return current.parent_path();
  }
  throw std::runtime_error("Unable to locate the repository root.");
}

std::string read_text(const std::filesystem::path& path) {
  std::ifstream input(path);
  if (!input) throw std::runtime_error("Unable to read " + path.string());
  std::ostringstream content;
  content << input.rdbuf();
  return content.str();
}

void expect_contains(const std::string& text, const std::string& expected,
                     const char* message) {
  if (text.find(expected) == std::string::npos) {
    throw std::runtime_error(message);
  }
}

void expect_omits(const std::string& text, const std::string& stale,
                  const char* message) {
  if (text.find(stale) != std::string::npos) {
    throw std::runtime_error(message);
  }
}

}  // namespace

int main() {
  const std::filesystem::path root = repo_root();
  const std::string assumptions =
      read_text(root / "docs" / "MODEL_ASSUMPTIONS.md");
  const std::string results = read_text(root / "results" / "README.md");
  const std::string readme = read_text(root / "README.md");
  const std::string cli =
      read_text(root / "src" / "trace_engine_v2" / "part_016.inc");
  const std::string report =
      read_text(root / "docs" / "CROBAT_MODEL_REPORT.md");

  // The generic pre-rewrite screen stays retired while the current Crobat model
  // uses a separate registry, CLI, artifact, and report:
  // Crobat V card data: https://api.pokemontcg.io/v2/cards/swsh3-104
  // Active CLI: https://github.com/FlareZ123/pokemon-sims/blob/main/src/trace_engine_v2/part_016.inc#L250-L330
  // Reproduction contract: https://github.com/FlareZ123/pokemon-sims/blob/main/README.md#model-crobat-v-swaps
  // Scoped matrix: https://github.com/FlareZ123/pokemon-sims/blob/main/results/crobat_variant_model.csv
  // Generated report: https://github.com/FlareZ123/pokemon-sims/blob/main/docs/CROBAT_MODEL_REPORT.md
  // Completed implementation: https://github.com/FlareZ123/pokemon-sims/issues/1394
  // Confirmed documentation bug: https://github.com/FlareZ123/pokemon-sims/issues/1511
  expect_contains(assumptions, "retired generic `variant_results.csv`",
                  "MODEL_ASSUMPTIONS.md lost the generic-screen identity.");
  expect_contains(assumptions, "remains unsupported",
                  "MODEL_ASSUMPTIONS.md no longer retires the generic screen.");
  expect_contains(assumptions, "`--model-crobat` and `--model-variant`",
                  "MODEL_ASSUMPTIONS.md omits the current Crobat commands.");
  expect_contains(assumptions, "`results/crobat_variant_model.csv`",
                  "MODEL_ASSUMPTIONS.md omits the scoped Crobat matrix.");
  expect_contains(assumptions, "`docs/CROBAT_MODEL_REPORT.md`",
                  "MODEL_ASSUMPTIONS.md omits the generated Crobat report.");
  expect_contains(assumptions, "outside `deck_registry()` and `--all-decks`",
                  "MODEL_ASSUMPTIONS.md lost the registry boundary.");
  expect_omits(
      assumptions,
      "must not be reused until a current variant generator, tests, and results are restored",
      "MODEL_ASSUMPTIONS.md still uses the ambiguous restoration condition.");

  expect_contains(results, "retired generic `variant_results.csv`",
                  "results/README.md lost the generic-screen identity.");
  expect_contains(results, "It remains unsupported",
                  "results/README.md no longer retires the generic screen.");
  expect_contains(results, "`--model-crobat` writes `results/crobat_variant_model.csv`",
                  "results/README.md omits the active scoped matrix.");
  expect_contains(results, "`--model-variant` reproduces one temporary derivative",
                  "results/README.md omits the Crobat trace command.");
  expect_contains(results, "outside `deck_registry()` plus `--all-decks`",
                  "results/README.md lost the registry boundary.");
  expect_omits(results,
               "It must not be reused until variants are regenerated by this engine.",
               "results/README.md still uses the ambiguous restoration condition.");

  expect_contains(readme, "--model-crobat",
                  "README.md lost the Crobat matrix command.");
  expect_contains(cli, "--model-variant",
                  "The CLI lost the one-variant trace option.");
  expect_contains(report, "temporary Crobat V swaps",
                  "The Crobat report lost its scoped modeling identity.");
  return 0;
}
